/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AcoAnimate {}
}

declare global {


  interface HTMLAcoAnimateElement extends Components.AcoAnimate, HTMLStencilElement {}
  var HTMLAcoAnimateElement: {
    prototype: HTMLAcoAnimateElement;
    new (): HTMLAcoAnimateElement;
  };
  interface HTMLElementTagNameMap {
    'aco-animate': HTMLAcoAnimateElement;
  }
}

declare namespace LocalJSX {
  interface AcoAnimate {}

  interface IntrinsicElements {
    'aco-animate': AcoAnimate;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'aco-animate': LocalJSX.AcoAnimate & JSXBase.HTMLAttributes<HTMLAcoAnimateElement>;
    }
  }
}


