/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AcoAccordion {
    'title': string;
  }
}

declare global {


  interface HTMLAcoAccordionElement extends Components.AcoAccordion, HTMLStencilElement {}
  var HTMLAcoAccordionElement: {
    prototype: HTMLAcoAccordionElement;
    new (): HTMLAcoAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'aco-accordion': HTMLAcoAccordionElement;
  }
}

declare namespace LocalJSX {
  interface AcoAccordion {
    'title': string;
  }

  interface IntrinsicElements {
    'aco-accordion': AcoAccordion;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'aco-accordion': LocalJSX.AcoAccordion & JSXBase.HTMLAttributes<HTMLAcoAccordionElement>;
    }
  }
}


